### ISSUE TITLE
Checklist to launch the 2023 theme

### ISSUE THREAD

**Issue by drewbrew** [djangocon/2023.djangocon.us#76]
- [x] Remove the schedule link from the homepage
- [x] On /sponsors/information, change the copy to reflect that sponsorship is indeed open (#77)
- [x] On /sponsors/information, add a mastodon link next to twitter (#77)
- [x] On /sponsors/information, remove that the lanyard sponsorship is claimed _or_ add the lanyard sponsor to the sponsor list
- [x] Footer: add a mastodon link to https://fosstodon.org/@djangocon
- [x] /about: fix the talk dates and remove the full schedule link (for now) (#79)
- [x] /conduct: update the CoC team to include Adrienne, Tim, and Peter, and remove departed board members/organizers (#78)
- [x] /faq: update the sponsorship section for 2023 (#80)
- [x] /covid/:  is that white space between the policy and the footer supposed to be there?
- [x] Update favicon to new font?

**Comment by mtrythall** [comment]
Bottom space removed on /covid/ (and other pages). Good catch: 

https://github.com/djangocon/2023.djangocon.us/pull/75/commits/141265278f113011709e91183128edaddd17b261

**Comment by drewbrew** [comment]
Nice!

**Comment by mtrythall** [comment]
Hit the issues I could here. Rest seem like content.

**Comment by drewbrew** [comment]
Thanks, @mtrythall!
